version: '3.3'

services:
  backend:
    container_name: backend
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    command: python server.py
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - my_network
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    depends_on:
      - backend
    restart: always
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  my_network:
    driver: bridge