version: '3.3'

services:
  backend:
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    command: python server.py
    cap_add:
      - NET_BIND_SERVICE